services:
  # ──────────────────────────────────────────────────────────────────────────────
  # PostgreSQL database
  db:
    image: postgres:17
    restart: unless-stopped
    hostname: db
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: ChangeMe123!
      POSTGRES_DB: appdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  # ──────────────────────────────────────────────────────────────────────────────
  # Express API server
  server:
    image: alucardikanno/db-scheme-editor-server:latest
    restart: unless-stopped
    hostname: server
    depends_on:
      - db
    environment:
      PORT: 4000
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: appdb
      PGUSER: appuser
      PGPASSWORD: ChangeMe123!
    ports:
      - '4000:4000'

  # ──────────────────────────────────────────────────────────────────────────────
  # Next.js frontend
  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_ENDPOINT: http://localhost:4000/api
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - '3000:3000'

volumes:
  db_data: